<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.transform_text' shared autowired service.

include_once $this->targetDirs[3].'/src/EntradaBundle/Services/ServiceEntrada.php';

return $this->services['app.transform_text'] = new \EntradaBundle\Services\ServiceEntrada();
