<?php

namespace LoginBundle\Repository;

use EntradaBundle\EntradaBundle;

/**
 * usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * string
     */
    const USER_ROL = 'Usuario';

    /**
     * string
     */
    const USER_ADMIN = 'Administrador';

    /**
     * string
     */
    const USER_ALTA = 'Alta';

    /**
     * string
     */
    const USER_BAJA= 'Baja';

    public function getQueryTable(){
        return $this->createQueryBuilder('u')
            ->select('u');
    }
}
