entrada_homepage:
    path:     /blog
    defaults: { _controller: EntradaBundle:Default:index }

entrada_edit:
    path: /edit
    defaults: { _controller: EntradaBundle:Default:editEntrada}

entrada_delet:
    path: /delet
    defaults: { _controller: EntradaBundle:Default:deletEntrada}