entrada:
    resource: "@EntradaBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
