<?php

namespace EntradaBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * EntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEntradas()
    {
        $qb = $this->createQueryBuilder('entrada');
        return $qb->select('entrada')
            ->join(
                'entrada.user','user')
            ->where(
                $qb->expr()->eq('user.active',':active')
            )->setParameter('active',1)
            ->getQuery()
            ->getResult();
    }
}
