<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIl5zev9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIl5zev9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIl5zev9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIl5zev9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIl5zev9\appProdProjectContainer([
    'container.build_hash' => 'Il5zev9',
    'container.build_id' => '408697bc',
    'container.build_time' => 1576000291,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIl5zev9');
