login:
    path:   /
    defaults:   { _controller: LoginBundle:Default:index }

registro:
    path:   /registro/
    defaults:   { _controller: LoginBundle:Default:registro }

logout:
    path:   /salir
    defaults:   { _controller: LoginBundle:Default:logout}

recuperar_password:
    path:   /recuperar
    defaults:   { _controller: LoginBundle:Default:recuperar}

log-in:
    path:   /login
    defaults:   { _controller: LoginBundle:Default:login}

api-token:
    path:   /token/get
    defaults:   { _controller: LoginBundle:Token:generateToken}
    methods:    POST