registro:
    path:     /registro/
    defaults: { _controller: LoginBundle:Default:registro }

login:
    path:     /
    defaults: { _controller: LoginBundle:Default:index }

logout:
    path: /salir
    defaults: { _controller: LoginBundle:Default:logout}

recuperar_password:
    path: /recuperar
    defaults: { _controller: LoginBundle:Default:recuperar}