<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.generate_code' shared autowired service.

include_once $this->targetDirs[3].'/src/LoginBundle/Services/ServiceUser.php';

return $this->services['app.generate_code'] = new \LoginBundle\Services\ServiceUser();
