home_homepage:
    path:     /home
    defaults: { _controller: HomeBundle:Default:index }

profile:
    path: /profile
    defaults: { _controller: HomeBundle:Default:profile}

home_profile:
    path: /profile/home/
    defaults: { _controller: HomeBundle:Default:profileHome}

list_user_ajax:
    path: /list/ajax
    defaults: { _controller: HomeBundle:Default:ajaxListUser}

list_user:
    path: /list
    defaults: { _controller: HomeBundle:Default:list}



