<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXurl6vg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXurl6vg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXurl6vg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXurl6vg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXurl6vg\appDevDebugProjectContainer([
    'container.build_hash' => 'Xurl6vg',
    'container.build_id' => '9bc2c874',
    'container.build_time' => 1576265720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXurl6vg');
