<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6da8css\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6da8css/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6da8css.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6da8css\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6da8css\appDevDebugProjectContainer([
    'container.build_hash' => '6da8css',
    'container.build_id' => 'ac9f2b3b',
    'container.build_time' => 1576174649,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6da8css');
