<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zfkjbx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zfkjbx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6zfkjbx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6zfkjbx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6zfkjbx\appDevDebugProjectContainer([
    'container.build_hash' => '6zfkjbx',
    'container.build_id' => '4fc656e8',
    'container.build_time' => 1576089773,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6zfkjbx');
